version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: orderflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: orderflowdb
      POSTGRES_USER: orderflow
      POSTGRES_PASSWORD: secret123
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
